Firefox < 50 support
In Firefox < 50 (https://developer.mozilla.org/en-US/Firefox/Releases/50#DOM) forEach requires an Array and was failing with:
`TypeError: document.querySelectorAll(...).forEach is not a function`