snippet: fix Firefox < 50 support
In Firefox < [50][0] forEach requires an Array and was failing with:
`TypeError: document.querySelectorAll(...).forEach is not a function`.

[0]: https://github.com/indutny/vote.now/pull/2.patch